### ISSUE TITLE
Include Matlab support for Git

### ISSUE THREAD

**Issue by mfurseman** [dls-controls/dls_ade#50]
There is now an area in Gitolite for matlab. It would be useful to be able to release from it! It seems that only the list of areas and the matlab.sh release scripts would require changing for this.

**Comment by nickbattam** [comment]
The list of areas is repeated across a number of the scripts; if supported is added to dls-release it would make sense to add it to create-new-module, checkout-module etc at the same time.

**Comment by GDYendell** [comment]
It could possibly just be handled in the shared argument parser. Those checks in individual scripts may be unnecessary.

https://github.com/dls-controls/dls_ade/blob/master/dls_ade/argument_parser.py#L5

Do all scripts share the same limitations?

**Comment by nickbattam** [comment]
There is custom area code in many of the scripts, e.g.:
https://github.com/dls-controls/dls_ade/blob/master/dls_ade/dls_list_releases.py#L98
and 
https://github.com/dls-controls/dls_ade/blob/master/dls_ade/get_module_creator.py
