### ISSUE TITLE
System Test Instructions

### ISSUE THREAD

**Issue by GDYendell** [dls-controls/dls_ade#76]
Improve system test instructions and setup scripts so that they just work.

**Comment by GDYendell** [comment]
There may be RHEL version inconsistencies or something else. But, sometimes I get 
`Traceback (most recent call last): File "push_required_repos.py", line 6, in <module> from dls_ade import Server ImportError: No module named dls_ade`
and sometimes I get
`Traceback (most recent call last): File "push_required_repos.py", line 6, in <module> from dls_ade import Server File "/scratch/work/common/python/RHEL7-x86_64/dls_ade/prefix/lib/python2.7/site-packages/dls_ade-0.0-py2.7.egg/dls_ade/__init__.py", line 1, in <module> from gitoliteserver import GitoliteServer as Server File "/scratch/work/common/python/RHEL7-x86_64/dls_ade/prefix/lib/python2.7/site-packages/dls_ade-0.0-py2.7.egg/dls_ade/gitoliteserver.py", line 8, in <module> from dls_ade.gitserver import GitServer File "/scratch/work/common/python/RHEL7-x86_64/dls_ade/prefix/lib/python2.7/site-packages/dls_ade-0.0-py2.7.egg/dls_ade/gitserver.py", line 5, in <module> from dls_ade.vcs_git import Git, git File "/scratch/work/common/python/RHEL7-x86_64/dls_ade/prefix/lib/python2.7/site-packages/dls_ade-0.0-py2.7.egg/dls_ade/vcs_git.py", line 3, in <module> import git ImportError: No module named git`

**Comment by willrogers** [comment]
So I caused some of the problems we're now trying to solve in 860e9ac2ac4fd47e8b21eefb4e263933aca40bad.

Previously the script `setup_testing_environment.sh` had three arguments, which made it tedious to use. I figured we only needed one, but I apparently made some assumptions that do not always hold and now we're trying to patch it up again.
